# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: 
      - main
      - a[0-9]                   # CI on a1-a9 assignment branches

  pull_request:
    branches: 
      - main
      - a[0-9]                   # CI on a1-a9 assignment branches

jobs:
  build:
    runs-on: ubuntu-latest     

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: Cloud
          POSTGRES_PASSWORD: cloud
          POSTGRES_PORT: 5432
          POSTGRES_USER: cloud
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 21.6.1
        uses: actions/setup-node@v4
        with:
          node-version: 21.6.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint codebase
        run: npm run lint

      - name: Execute tests
        run: npm test

      - name: Build source code
        run: npm run build 
      
      - name: Archive production artifacts
        run: tar -czvf webapp.tar.gz dist

      - name: Deploy to Droplet[Dev]
        if: ${{ startsWith(github.ref, 'refs/heads/a') || startsWith(github.base_ref, 'a')}}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/droplet.key
          chmod 600 ~/.ssh/droplet.key
          cat >>~/.ssh/config <<END
          Host droplet
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/droplet.key
            StrictHostKeyChecking no
          END

          scp -i ~/.ssh/droplet.key webapp.tar.gz $SSH_USER@$SSH_HOST:/home/node
          ssh -i ~/.ssh/droplet.key $SSH_USER@$SSH_HOST "
            mkdir -p /home/node/webapp
            cd /home/node
            rm -rf webapp
            cd webapp
            tar -xvf /home/node/webapp.tar.gz
            pm2 delete server || : && pm2 start /home/node/server.js -i 1 --name 'server'
          "
        env:
          SSH_USER: ${{ secrets.DROPLETUSER }}
          SSH_KEY: ${{ secrets.DROPLETSSHKEY }}
          SSH_HOST: ${{ secrets.DROPLETIP }}
