name: webapp test

on:
  pull_request:
    branches: 
      - main
      - packer                   # CI on test branch

jobs:
  test:
    runs-on: ubuntu-latest     

    steps:
      - name: Enable Postgres and create database with user # PostgreSQL service is preinstalled on ubuntu-latest.
        env:
          DB_NAME: ${{ secrets.INTEGRATION_TEST_DB_NAME }}
          DB_USER: ${{ secrets.INTEGRATION_TEST_DB_USER }}
          DB_PASSWORD: ${{ secrets.INTEGRATION_TEST_DB_PASSWORD }}
        run: |
          sudo service postgresql start
          sudo -u postgres psql -c 'CREATE DATABASE "'$DB_NAME'";'
          sudo -u postgres psql -c "CREATE USER "$DB_USER" WITH PASSWORD '"$DB_PASSWORD"';"
          sudo -u postgres psql -c 'GRANT ALL PRIVILEGES ON DATABASE "'$DB_NAME'" TO '$DB_USER';'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 21.6.1
        uses: actions/setup-node@v4
        with:
          node-version: 21.6.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint codebase
        run: npm run lint

      - name: Execute tests
        run: npm test

